client/cache/IMyCache.cs, ff-netF48-server-sdk.csproj
- Project updated to target both netstandard2 and net461. In both scenarios, we are using the same 3rd party dependency libraries
- Returning read-only cache interface
=> Create multi-target project and update on cache interface

client/api/CfClient.cs
- Removed initialization from getInstance method, into separate initialization routine, and change getInstance method to thread safe Instance property.
- Signature of public API is updated and no longer contains asynchronous keyword, as results are returned from local cache synchronously.  All other internal functions are now private. 
NOTE: Sample app will be updated to reflect changes in SDK.
=> Refactor cfclient

client/dto/Target.cs
If creating a target via TargetBuilder, and private attributes aren't specified via `TargetBuilder.PrivateAttributes`, the `privateAttributes` member never gets initialized, which becomes a problem when analytics get published here: https://github.com/drone/ff-dotnet-server-sdk/blob/main/client/api/analytics/AnalyticsPublisherService.cs#L102
=> Initialize `privateAttributes` in TargetBuilder

client/api/CfClient.cs, tests/ff-server-sdk-example/Program.cs
- Updating interface to match "older" version for backward compatibility.
BoolVariation --> boolVariation
StringVariation --> stringVariation
NumberVariation --> numberVariation
JsonVariation --> jsonVariation
Note that C# has PascalCase naming conversion for Method name, and we are reverting to camelCase which results in build warnings, but we are keeping backward compatibility with older clients. 
@milos85vasic
=> Update interface to keep backward compatibility

client/api/Evaluator.cs
LINQ query .First will throw an exception if value is not found, so we should use FirstOrDefault which returns null in case if element doesn't exist
=> Fix crash on identifier comparison

client/api/PollingProcessor.cs, client/api/Repository.cs, client/cache/FileMapStore.cs, tests/ff-server-sdk-test/VersionTest.cs
- In case if Version field is missing or is equal to 0, always use content from server.
- Update for Local storage serialization and deserialization based on Newtonsoft library internal processing.
- Unit test update.
=> Support for missing Version field in response from server 

README.md, examples/getting_started/getting_started.csproj, ff-netF48-server-sdk.csproj
**What**
https://www.nuget.org/packages/ff-dotnet-server-sdk
Updates the package name 
from ff-netF48-server-sdk
to ff-dotnet-server-sdk
Updates readmen to reflect this
**Why**
Issues with publishing SDK Nuget packages, also just generally looks better
=> MAINT - Update package naming

client/api/analytics/AnalyticsEventHandler.cs, client/api/analytics/AnalyticsPublisherService.cs
**Changes**
Updating the analytics debug logging. 
Logging every time a metric was added is incredibly noisy and not that accurate because it doesn't give you an indication of what actually gets sent to the /metrics endpoint at the end.
Replaced it with a log where we dump the analytics object before sending the metrics request. This will let us and customers debug what is being sent and why targets may not be being added.
=> (FFM-4835) Debug logging for analytics

client/api/Evaluator.cs, tests/ff-server-sdk-test/EvaluatorTest.cs, tests/ff-server-sdk-test/TestModel.cs, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
[FFM-5307] - .NET SDK - Fix for prereq identifier + update JSON parse to use latest tests
What
When a feature depends on another prereq feature being true, the evaluation fails if the value and identifier are different values in the prereq. Update code to use latest ff-test-cases JSON format which adds ~90 additional tests. Some additional fixes were needed including Null reference exception and incorrect OR handling in groups when latest JSON was used.
Why
The checkPreRequisite() method incorrectly uses the value of the prereq instead of the identifier.
Testing
Tested locally with new ff-test-cases JSON + sanity checks with example program
[FFM-5307]: https://harness.atlassian.net/browse/FFM-5307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-5307] - .NET SDK - Fix for prereq identifier + update ff-test-cases

client/api/InnerClient.cs, client/connector/EventSource.cs, client/connector/HarnessConnector.cs, examples/getting_started/getting_started.csproj, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/connector/EventSourceTest.cs, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
FFM-6877 - Dropped SSE connections are not being detected
What
SSE EventSource does not detect that a connection may have dropped. This update removes calls to StreamReader's EndOfStream/ReadLineAsync which will hang forever if the socket has no data arriving. Instead, read and parse the lines directly from the SSE source and add a CancellationTokenSource with a timeout of 60 seconds, if no data arrives.
Why
We're getting customer reports of flags not updating correctly when the SDK has been left running for some time.
Testing
Added new Wiremock tests for testing EventSource, also manual testing
=> FFM-6877 - Dropped SSE connections are not being detected

client/connector/HarnessConnector.cs, ff-netF48-server-sdk.csproj, ff-netF48-server-sdk.sln, tests/ff-server-sdk-test/HarnessConnectorTest.cs
this adds Harness-SDK-Info, Harness-EnvironmentID, Harness-AccountID http headers
- Feature parity with other sdks 
- used to help with logging/debugging
=> feat: [FFM-7477]: Adding additional headers to SDK requests

client/api/analytics/AnalyticsPublisherService.cs
Correctly pulls in the Assembly version when sending metrics
Fixes an issue where the SDK version (aka Assembly version) was being sent incorrectly in the metrics payload
Manual
=> [FFM-6904]: FFM-6904-sending-sdk-version-in-metrics-payload

client/api/AuthService.cs, client/api/Evaluator.cs, client/api/InnerClient.cs, client/api/PollingProcessor.cs, client/api/UpdateProcessor.cs, client/api/analytics/AnalyticsPublisherService.cs, client/connector/EventSource.cs, client/connector/HarnessConnector.cs, client/polling/ShortTermPolling.cs, tests/ff-server-sdk-test/connector/EventSourceTest.cs
FFM-7472 - Standardise Init / Auth / Close / Polling / Streaming / Metrics log messages and error messages
What
Adding standardised SDK error codes + pushing some logs down to debug to reduce noise
Why
Each SDK uses different log messages for its lifecycle. We want to standardise messages across SDKs with a unique code.
Testing
Manual testing + unit testing
=> (FFM-7472): Standardise log messages

.gitignore, client/api/Evaluator.cs, client/api/analytics/AnalyticsPublisherService.cs
WHAT: When a user passes in a `null` as the Target value of an evaluation
request, the metrics processor received a NullPointerException trying to parse
the target and add it to the TargetData.
FIX: The fix is to allow the logging and evaluation logic to handle the null
value as opposed to trying to dereference the Target attributes. Also in the
prepareMessageBody function, to handle the Target Data parsing separately from
the evaluation metrics, so that evaluation counts still get sent in, even if
the Target data has a null value.
=> (FFM-8128): Fixes handling of null targets 

client/api/AuthService.cs, client/connector/HarnessConnector.cs, ff-netF48-server-sdk.csproj
- When the ff relay proxy is being used, the accountID is not currently present as a claim in the auth JWT. This fix adds a check to see if the accountID is present before including it in the additional headers. 
- Now logs any exceptions that occur when authenticating
The SDK would fail to auth when using the relay proxy 
Tested on latest relay proxy version, and without the proxy
=> FFM-8686  Only include accountID if it is present in the JWT

client/connector/HarnessConnector.cs
[FFM-9207] - Fix version/account/env meta data reported in headers
What
Fixes the following headers to report the correct info: Harness-SDK-Info, Harness-EnvironmentID, Harness-AccessID
Why
Metadata is currently invalid and doesn't show any useful information
Testing
Manual + proxy
[FFM-9207]: https://harness.atlassian.net/browse/FFM-9207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9207] - Fix version/account/env meta data reported in headers

client/api/PollingProcessor.cs
[FFM-9220] - SDK should enforce minimum poll interval
What
Don't allow poll interval to be less than 1 minute. If it is, use 60 seconds as the interval and log a warning.
Why
Ensure SDK usage remains fair and backend servers are not overloaded with polling requests
Testing
Manual
[FFM-9220]: https://harness.atlassian.net/browse/FFM-9220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9220] - SDK should enforce minimum poll interval

README.md, build.sh, client/api/AuthService.cs, client/api/CfClient.cs, client/api/Config.cs, client/api/Evaluator.cs, client/api/InnerClient.cs, client/api/PollingProcessor.cs, client/api/Repository.cs, client/api/UpdateProcessor.cs, client/api/analytics/AnalyticsManager.cs, client/api/analytics/AnalyticsPublisherService.cs, client/cache/FileMapStore.cs, client/connector/EventSource.cs, client/connector/FileWatcher.cs, client/connector/HarnessConnector.cs, client/connector/JsonContractResolver.cs, client/connector/LocalConnector.cs, client/polling/ShortTermPolling.cs, examples/getting_started/Program.cs, examples/getting_started/getting_started.csproj, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/AuthService.cs, tests/ff-server-sdk-test/EvaluatorTest.cs, tests/ff-server-sdk-test/HarnessConnectorTest.cs, tests/ff-server-sdk-test/api/CfClientTest.cs, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs, tests/ff-server-sdk-test/connector/EventSourceTest.cs, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
FFM-9392 - Support Microsoft.Extensions.Logging
What
Remove hardcoded Serilog statements and namespace reference and replace them ILogger statements. Also remove string interpolation and use templates instead.
Logging can now be configured externally using any preferred logging framework. For example, using `Serilog.Extensions.Logging` and `Serilog.Sinks.Console` you can pass in a factory directly via `Config.LoggerFactory`:
```
Log.Logger = new LoggerConfiguration()
.MinimumLevel.Information()
.WriteTo.Console().CreateLogger();
var loggerFactory = new SerilogLoggerFactory(Log.Logger);
var ffConfig = Config.Builder()
.LoggerFactory(loggerFactory)
.Build();
var client = new CfClient(API_KEY, ffConfig);
await client.InitializeAndWait();
```
Alternatively you can use dependency injection
``` …
```
=> FFM-9392 - Support Microsoft.Extensions.Logging

client/api/Config.cs, client/connector/HarnessConnector.cs, ff-netF48-server-sdk.sln, tests/tls-example/Program.cs, tests/tls-example/tls-example.csproj
[FFM-7007] - .NET SDK - TLS - support custom CAs
What
Allow the SDK user to provide a custom TLS CA via the new config `TlsTrustedCAs` API. This property takes a list of Certificate Authorities in X.509 format via .NET's [X509Certificate2](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2?view=net-7.0) class. You should provide the CA that will be used to validate the certificate sent by the server along with all its intermediate CAs right up until the root.
Prebundle and system provided CAs are switched off to allow servers to be ring-fenced. All CAs need to be provided.
Why
We currently rely on pre-installed CA bundles in the system for TLS connections, e.g. those host names signed by public CAs, it's useful to provide …
=> [FFM-7007] - .NET SDK - TLS - support custom CAs

tests/ff-server-sdk-test/api/CfClientTest.cs, tests/ff-server-sdk-test/connector/EventSourceTest.cs, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
[FFM-9472] - Update wiremock to latest version 1.5.35
What
Update to the latest version
Why
Get latest security updates
Testing
Manual
[FFM-9472]: https://harness.atlassian.net/browse/FFM-9472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9472] - Update wiremock to latest version 1.5.35

tests/ff-server-sdk-test/ff-server-sdk-test.csproj
[FFM-9474] - Update NuGet.Frameworks to version 6.5.1
What
Update NuGet.Frameworks to version 6.5.1 so that a transitive dependency in Microsoft.NET.Test.Sdk is also updated
Why
Removes CVE 2023-29337
Testing
Manual + test grid
[FFM-9474]: https://harness.atlassian.net/browse/FFM-9474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9474] - Update NuGet.Frameworks to version 6.5.1

README.md, examples/getting_started/Program.cs, examples/getting_started/getting_started.csproj
FFM-9206 - Various cleanups to README and examples 
What
Update examples to fresh new loggers + update example in README to add --framework option. Also set getting started to use 1.2.*
Testing
Confirmed getting started is working ok:
docker run -v $(pwd):/app -w /app -e FF_API_KEY=$FF_API_KEY mcr.microsoft.com/dotnet/sdk:6.0 dotnet run --framework net6.0 --project examples/getting_started/
[10:20:10 INF] SDKCODE(auth:2000): Authenticated ok [10:20:10 INF] SDKCODE(metric:7000): Metrics thread started [10:20:10 INF] SDKCODE(stream:5000): SSE stream connected ok [10:20:10 INF] SDKCODE(init:1000): The SDK has successfully initialized [10:20:10 INF] SDK version: 1.2.1.0
Flag 'harnessappdemodarkmode' = True
Flag 'harnessappdemodarkmode' = True
Flag 'harnessappdemodarkmode' = True
Flag …
=> FFM-9206 - Various cleanups to README and examples 

.gitignore, Connected Services/HarnessOpenMetricsAPIService/HarnessOpenMetricsAPI.cs, Connected Services/HarnessOpenMetricsAPIService/HarnessOpenMetricsAPI.nswag.json, Connected Services/HarnessOpenMetricsAPIService/metrics-v1.yaml, client/connector/HarnessConnector.cs, ff-netF48-server-sdk.csproj, ff-netF48-server-sdk.csproj.user
[FFM-9659] - Fix targets not updating correctly
What
Fix API definition for metrics which were missing the cluster identifier. Readd this back on when posting metrics. Also some additional fixes to remove meta data we don't need added by the JSON lib.
Why
Reports of targets not appearing correctly on UI
Testing
Manual
[FFM-9659]: https://harness.atlassian.net/browse/FFM-9659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9659] - Fix targets not updating correctly

client/connector/HarnessConnector.cs
[FFM-9725] - Fix hostname validation on custom TLS certs
What
Fix hostname matching to allow sub-domains to be accepted. Use EndsWith() for domains and Equals() for IPs. Note wildcard domains not supported.
Why
Code currently throws an exception on startup if cert is signed against e.g. ff.mydomain.com but SDK requests config.ff.mydomain.com
Testing
Manual
[FFM-9725]: https://harness.atlassian.net/browse/FFM-9725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9725] - Fix hostname validation on custom TLS certs

client/dto/Target.cs
[FFM-9750] - Mark private attributes for deprecation
What
We don't support private attributes and the original implementations were never fully completed. Mark them for removal.
[FFM-9750]: https://harness.atlassian.net/browse/FFM-9750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9750] - Mark private attributes for deprecation

client/api/Evaluator.cs, client/api/rules/DistributionProcessor.cs, client/api/rules/Strategy.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/api/rules/StrategyTest.cs
[FFM-9926] - Testgrid - % rollout - .NET SDK - Fix MM3 hash
**What**
Various fixes to MM3 hash to bring it in alignment with GoLang SDK
- Set MM3 seed to 0
- Fixed a problem with hash where GetHashCode() was used instead of BitConverter()
- If bucket_by attribute is missing, fall back to identifier + log new SDK code
- Additional debug statements for easier diagnostics
- Update unit tests
**Why**
Review SDKs to make sure Murmur3 hash calculations are consistent across SDKs and buckets mappings align for customers that rely on this feature.
**Testing**
New percentage rollout tests added to testgrid, these will be committed later
[FFM-9926]: https://harness.atlassian.net/browse/FFM-9926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9926] - Testgrid - % rollout - .NET SDK - Fix MM3 hash

client/connector/HarnessConnector.cs, ff-netF48-server-sdk.csproj
[FFM-9946] - Add `netstandard2.0`/`net461` targets
**What**
Adds the following targets to the SDK. `netstandard2.0` and `net461`
Note if using the SDK on a target older than .NET5 then the following config method will throw a 'not supported' exception: `Config.Builder().TlsTrustedCAs()` since the required APIs are not available on these older platforms.
**Why**
This allows us to increase our user-base to older .NET versions while disabling newer features these users may not require.
**Testing**
[FFM-9946]: https://harness.atlassian.net/browse/FFM-9946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9946] - Add netstandard2.0 support

build.sh, client/api/CfClientException.cs, client/api/PollingProcessor.cs, client/connector/HarnessConnector.cs, tests/ff-server-sdk-test/HarnessConnectorTest.cs, tests/ff-server-sdk-test/api/CannedResponses.cs, tests/ff-server-sdk-test/api/CfClientTest.cs, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
[FFM-9951] - Remove "Collection was modified" exception
**What**
Add some hardening, copy list before iterating, log exception details + additional null checks
Polling Processor will now keep trace of inner exceptions for more complete stacktraces.
**Why**
We're seeing reports of "Collection was modified; enumeration operation may not execute." in the field when the stream drops.
**Testing**
Manual + Unit tests
[FFM-9951]: https://harness.atlassian.net/browse/FFM-9951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  [FFM-9951] - Remove "Collection was modified" exception

client/api/AuthService.cs, client/api/CfClient.cs, client/api/InnerClient.cs, client/api/PollingProcessor.cs, client/connector/EventSource.cs, tests/ff-server-sdk-test/InitTest.cs, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
[FFM-10184] - WaitForInitialization updates
**What**
Unify old and new code to make WaitForInitialization() and legacy InitializeAndWait() work on the same latch. Also various updates and fixes with new (manual) unit tests added.
**Why**
Ensure all entrypoints into SDK are tested and find which code need to be deprecated.
**Testing**
[FFM-10184]: https://harness.atlassian.net/browse/FFM-10184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-10184] - WaitForInitialization updates

client/api/InnerClient.cs, tests/ff-server-sdk-test/InitTest.cs
**What**
Fixing notifications to correctly fire after changes in PR #95. Also add additional assertions to tests. Fix a minor issue where calling `Initialize()` twice on a `CfClient.Instance` didn't reset the internal sdk ready latch counter.
**Testing**
Manual + Testgrid
=> [FFM-10184] - WaitForInitialization notification updates

client/connector/HarnessConnector.cs, ff-netF48-server-sdk.csproj
[FFM-10222] - Config ConnectionTimeout (milliseconds) being treated as seconds internally
**What**
Config.ConnectionTimeout is marked as milliseconds in the public API but treated as seconds by HarnessConnector
**Testing**
Manual
[FFM-10222]: https://harness.atlassian.net/browse/FFM-10222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-10222] - Config ConnectionTimeout (milliseconds) being treated as seconds internally

client/api/analytics/AnalyticsPublisherService.cs, client/dto/Target.cs, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs
-  Uses thread safe dictionaries for the targets collections instead of unsafe HashSet which could result in thread contention exceptions
- Fixes duplicate targets being sent and stored. Targets are now equal if their identifier and attributes are the same.
- New unit tests
- Manual 
- TestGrid metrics
=> FFM-10287 Fix thready safety metrics issue

tests/ff-server-sdk-test/ff-server-sdk-test.csproj
**What**
Upgrade wiremock.net.fluentassertions to 1.5.46
**Why**
STO is reporting vulnerabilities on the pipelines are breaking the build check if updating to .46 removes CVE-2020-27853
**Testing**
Manual
=> FFM-10410 - Upgrade wiremock

client/api/InnerClient.cs, client/api/analytics/AnalyticsManager.cs, client/api/analytics/AnalyticsPublisherService.cs, client/dto/Analytics.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs
Previously, we didn't differentiate between `evaluation` and `target` metrics in terms of storing and processing them as separate entities. This meant that we could not use the `global target` feature to shrink `evaluation` metrics. The `global target` feature means that a unique evaluation metric is a combination of unique `flag ` + `variation` values, where as before the `target` would have been used.  
This change separates out the metric types as follows:
1. The original single cache is used. I have not created a separate cache. 
2. The metric types are differentiated using a subclassing approach, where we store each type in the same cache.
3. When we come to process the metrics, we check the type accordingly. 
Also enables global target feature. 
- Without `global target` feature
- …
=> FFM-10602 Separate `Analytics` into `EvaluationAnalytics` and `TargetAnalytics` 

client/api/Config.cs, client/api/Evaluator.cs, client/api/InnerClient.cs, client/api/analytics/AnalyticsManager.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/EvaluatorTest.cs, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs
Previously, when an evaluation, prior to storing the record to the cache it would flush and send metrics if the buffer size was exceeded. This is problematic for two reasons:
1. race condition because the metrics thread can also modify that cache. 
2. the evaluation thread should not be sending any network requests which can result in added latency.
Instead of flushing and sending metrics if the buffer size is exceeded, we not stop recording metrics for the period of that interval, and log a warning.
This also adds a config option that users can set a max cache size of 4096 if required.
If metrics is disabled, the evaluation thread can still post metrics if it detected the buffer size was at capacity. 
Return early, don't attempt to do any metrics related operations if metrics is disabled …
=> FFM-10602 Don't make network request from Evaluation thread

client/api/analytics/AnalyticsManager.cs, client/api/analytics/AnalyticsPublisherService.cs, client/dto/Target.cs, docs/further_reading.md, ff-netF48-server-sdk.csproj
- Previously, we were maintaining two collections for managing seen targets. This is not needed is wasteful. 
- Removes `StagingSeenTargets`
- Now checks `SeenTargets` immediately after an evaluation has been made in `pushToCache`, to avoid storing a target if it has been seen.
- This has a performance boost - we are now able to make 92K more evaluations per second. 
- No longer stores private targets in the cache. Previously they were stored and only disregarded at time of the push to the backend. 
Unit tests still passing
Manual test of seen targets behaviour using prod 2 account
=> FFM-10837 Remove redundancy in the seen target process

client/api/analytics/AnalyticsPublisherService.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs
- The `privateAttributes` check was removed in https://github.com/harness/ff-dotnet-server-sdk/pull/105 This unfortuntaely removed the attributes from being added in general to the target metrics payload, which has been fixed in this PR. 
- Makes `SeenTargets` an instance variable as this should be instance specific. 
Manual - target and correct attributes appear in UI.
=> FFM-10943 Fix target attributes not being sent

client/api/AuthService.cs, client/api/PollingProcessor.cs, examples/tls-example/Program.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/api/CfClientTest.cs
[FFM-11002] - Fix exception handling in auth success callback
**What**
- Avoid allowing exceptions thrown inside the auth success callback to trickle up to the auth service.
- On first poll catch any exceptions to allow poller to be started.
**Why**
If auth success callback threw an error the SDK would attempt to reauth even though it has authenticated ok previously. Also if there is a network error (or any other exception) thrown inside PollingProcessor's start() method then the poller will not be started. Failed polls should be treated as transient (e.g. network) and the next poll will allow the SDK to self heal.
**Testing**
[FFM-11002]: https://harness.atlassian.net/browse/FFM-11002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
=> [FFM-11002] - Fix exception handling in auth success callback

client/api/Evaluator.cs, client/api/InnerClient.cs, client/api/PollingProcessor.cs, client/api/ToStringHelper.cs, ff-netF48-server-sdk.csproj
- Refactors `Evaluate` method to immutability 
- Logs `null` flag/group objects which would indicate invalid cache state
- If the group can't be found, throws new `InvalidCacheState` ex which the variation methods catch, and returns the default variation.  The `InnerClient` variation methods then trigger a group cache refresh which is non-blocking.
- Much more additional logging of evaluation paths to aid in debugging
- Ran through TestGrid evaluation suite
- Manual with prod 2 account
=> FFM-11022 Evaluation class refactor

client/api/Config.cs, client/api/Evaluator.cs, client/api/InnerClient.cs, client/api/PollingProcessor.cs, ff-netF48-server-sdk.csproj
This adds cache recovery mechanism for flags and groups in the following ways (note the recovery can't be triggered more than once per minute to avoid overloading our API): 
Since a group cache lookup is determined by the flag, and if it's missing from the cache then we know the cache state is invalid, we now trigger one group cache refresh with timeout and a warning log, and attempt to evaluate one final time. If the same error occurs and we can't find the group even after a refresh, we return the default variation and log an error.
Not finding a flag in the cache doesn't necessarily mean invalid state; the user may have supplied a flag ID that doesn't exist in their project.  However, if the flag can't be found we attempt one refresh of the flag cache with timeout  + warning log. if it …
=> FFM-11022 Flag/Group cache recovery

ff-netF48-server-sdk.csproj
Security scanners work off the `PackageLicenseExpression` Property ([see deprecation info re `PackageLicenseUrl`](https://learn.microsoft.com/en-us/nuget/reference/nuspec#licenseurl))
Because you're using a straight Apache 2.0 license, you can just express that compliance via this expression
Ultimately the property propagates such that the nupgk bears the expression, and [nuget.org renders and extra line expressing this](https://www.nuget.org/packages/equinox.cosmosstore)
=> chore(License): Update to use PackageLicenseExpression

ff-netF48-server-sdk.csproj
Makes `System.Net.Http` a conditional import where it is only included for `net461` and `netstandard2.0`
`System.Net.Http` is included in .NET 5.0 onwards and is a redundant import, but we should still include it for the older TFMs we support to ensure backwards compatability
Sample app using a lockfile to determine dependencies brought in by the SDK:
-  targeting .NET 5.0 / .NET 6.0 / .NET 7.0 using lock file 
- targeting net461
- ![Screenshot 2024-05-21 at 15 31 51](https://github.com/harness/ff-dotnet-server-sdk/assets/23323369/819d3826-2364-4fa8-922b-a44d8d55055f)
=> FFM-11509 Make `System.Net.Http` conditional 

client/api/analytics/AnalyticsManager.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs
Since 1.5.0, a null pointer exception would occur if an evaluation was made with a `null` target when checking if the target was valid to be stored in analytics. 
This PR adds a null check to fix the issue. 
New unit test + manual sample app. 
Ran pipeline against PR
=> FFM-11537 Handle null target for target metrics + test

client/api/analytics/AnalyticsManager.cs, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs
Cherry picks the NPE patch from 1.6.9 back into `main` 
We needed to create a release branch to get a patch out that does not include recent changes to conditional imports of `System.Net.Http` 
Tested in https://github.com/harness/ff-dotnet-server-sdk/pull/122
=> FFM-11537 Cherry pick 1.6.9 patch

client/api/Evaluator.cs
[FFM-11551] - Remove excessive ToList() allocations in Evaluator
**What**
Remove calls to ToList() and iterate over the ICollection directly
**Why**
Profiling is showing we're doing some unnecessary work in the evaluator. Remove uneeded allocations and avoid copying to increase eval performance.
**Testing**
Testgrid
[FFM-11551]: https://harness.atlassian.net/browse/FFM-11551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-11551] - Remove excessive ToList() allocations in Evaluator

client/api/Evaluator.cs, client/api/InnerClient.cs
[FFM-11557] - Wrap log statements with if statements
**What**
Wrap some debug statements on the evaluation path with if statements so they don't get run when logging is disabled for that level. Also wrapped some warning loggers too
**Why**
We're seeing debug logs creating noise on the heap when log level is set to something higher. We want to prevent unnecessary objects on the heap/work for the GC.
**Testing**
Load + Testgrid
[FFM-11557]: https://harness.atlassian.net/browse/FFM-11557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-11557] - Wrap log statements with if statements

client/api/Config.cs, client/api/InnerClient.cs, client/api/analytics/AnalyticsManager.cs, client/api/analytics/AnalyticsPublisherService.cs, client/cache/MyCache.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/api/analytics/AnalyticsManagerTest.cs
Applies the following optimsations to the `SeenTargetsCache` to reduce memory footprint and decrease latency
- Keys on `targetIdentifier` instead of the full `Target` which was left over when targets were equal by ID + attributes. Now they are equal based on ID along so no need to store the full target. This should significantly reduce memory
- Sets configurable limit to cache size, defaulting to 500K targets. This will prevent unbounded memory growth. 
- Configurable `SeenTargetsCache` reset, defaulting to 12 hours. 
- For checking target existence, uses `ContainsKey` instead of `TryGetValue` as no need to get the value. This should improve performance. 
- For adding targets to both `SeenTargetsCache` and `TargetAnalyticsCache`, uses `TryAdd` instead of `AddOrUpdate` as we don't need to …
=> FFM-11549 SeenTargets cache memory improvements

ff-netF48-server-sdk.csproj
The first 1.7.0 RC used version `1.7.0-rc1` which was not a correct semver standard.  We have just released `1.7.0-rc.2` using correct semver versioning, and despite it being published to Nuget, is not being pulled correctly. `1.7.0-rc1` gets pulled instead.
This PR is to version it using the incorrect standard, and then we can use the correct standard for other RCs > 1.7.0
=> FFM-11549 1.7.0-rc2 bump

client/api/Evaluator.cs, client/api/Repository.cs, ff-netF48-server-sdk.csproj
[FFM-11585] - Sort rules when retrieving instead of per evaluation
**What**
Move the rules sorting into `SetSegment` similar to map caching so that it is only done once.
**Why**
Avoid the cost of sorting multiple times during evaluations when it is unnecessary. Some customer are using a lot of rules and this wastes CPU.
**Testing**
Load testing + testgrid
[FFM-11585]: https://harness.atlassian.net/browse/FFM-11585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-11585] - Sort rules when retrieving instead of per evaluation

client/api/InnerClient.cs, client/api/PollingProcessor.cs, client/api/UpdateProcessor.cs, client/api/analytics/AnalyticsManager.cs, client/connector/EventSource.cs, client/connector/HarnessConnector.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/connector/EventSourceTest.cs
On .NET 4.8, the stream was disconnecting after about one minute.  This was caused by the http client used in that version timing out despite it being a long lived streaming connection - this does not happen on newer .NET versions with different http client behaviour.  The stream was taking at least 70 seconds to reconnect depending on the polling interval used.
- This fix sets the SSE http client's timeout to `Infinity` and uses the heartbeat mechanism to kill any "dead" streams.  If a heartbeat isn't received in 35 seconds, the stream will abort and reconnect.  
- If the initial request doesn't resolve within 10 seconds, the stream will retry the connection. 
- Fixes the reconnection behaviour. Before, we would wait a fixed 130 seconds before attempting to reconnect which is excessively …
=> FFM-11573 Fix streaming issues for .NET 4.8

client/api/CfClient.cs, client/api/Evaluator.cs, client/api/InnerClient.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/EvaluatorTest.cs
This PR adds a new method `jsonVariationToken` which returns a `JToken` instead of `JObject`.   `jsonVariation` method has been marked as `Obsolete`.  
Also adds exception handling to `jsonVariation` to fix a crash if anything other than a JSON object was returned for a flag variation.
- Allows the SDK to accept `JObject/JArray/JValue` types.  
- This change allows all JSON variation types to be parsed as a `JToken` and returned to the user.  The user simply needs to use `JToken.DeepEquals` for comparisons.
JSON objects: Call new method in ff-testcases and testgrid.
JSON arrays:  manual testing using prod 2 account with flag and json array variation.  TestGrid doesn't currently support JSON arrays.
=> FFM-11548 Add new `jsonVariationToken` method and deprecate `jsonVariation`

client/api/Evaluator.cs
**Issue**
NumberVariation incorrectly logged the warning as `SDKCODE(eval:6001): Failed to evaluate String variation` when it failed, rather than Int variation like elsewhere in the code
=> fix: [FFM-11759]: fix incorrect number variation warning message

.github/workflows/codeql-analysis.yml, build.sh, client/api/AuthService.cs, client/api/CfClient.cs, client/api/CfClientException.cs, client/api/Evaluator.cs, client/api/InnerClient.cs, client/api/PollingProcessor.cs, client/api/Repository.cs, client/api/rules/DistributionProcessor.cs, client/api/rules/Strategy.cs, client/connector/HarnessConnector.cs, docs/further_reading.md, examples/getting_started/Program.cs, ff-netF48-server-sdk.csproj, tests/evaluation-load-test/evaluation-load-test.csproj, tests/ff-server-sdk-test/AuthService.cs
This PR addresses three issues:
1. Adds a new `FlagsLoaded` event: event contains a list of flag identifiers that have been cached.  It fires at least once when the SDK has initiailized succesfully, and then on each poll which will take place only if streaming is disabled or has fallen back to polling due to a disconnection.  A check is made that the event has been subscribed to before pulling the IDs from the cache as an optimisation.
2. Fixes the `WaitForInitialzation()` call not unblocking if auth fails:
- `401/403` errors are not retried and the call unblocks immediately and the SDK is placed into an un-initialized state.
- All other errors are retried up to 10 times, after which the call unblocks and the SDK is placed into un-init state. 
3. Stops a cache refresh if a flag/group …
=> FFM-11759 Add `FlagsLoaded` Event + Unblock WaitForInit call on auth failures

client/api/PollingProcessor.cs, client/connector/EventSource.cs
If `client.close()` was called, the stream would remain open.  This adds a new cancellation token that is used throughout streaming code to ensure that connections and loops exit when the SDK is closed.  Also ensures that the fallback polling mechanism isn't started under this circumstance. 
The client should close all connections when closed, to avoid a memory leak situation. 
.NET Core 5, 6, 7
.NET 4.8 on a Windows VM - this needs tested because the HTTP client behaves differently in this version for long lived streaming connections.
=> FFM-11801 Fix `client.close()` not exiting streaming 

build.sh, client/connector/HarnessConnector.cs, examples/getting_started/getting_started.csproj, examples/tls-example/tls-example.csproj, ff-netF48-server-sdk.csproj, tests/evaluation-load-test/evaluation-load-test.csproj, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
- Integrates community PR submission from https://github.com/harness/ff-dotnet-server-sdk/pull/138 for issue https://github.com/harness/ff-dotnet-server-sdk/issues/139
- Also removes `Disruptor` library as this has been unused since it was removed from Analytics code in 1.1.8: https://github.com/harness/ff-dotnet-server-sdk/compare/1.1.7...1.1.8 
- Tested all versions of .NET we support: 8.0 / 7.0 / 6.0 / 5.0 / 4.6.1 
- Tested 4.8 on a Windows VM
- Tested auth / streaming / polling / metrics
=> FFM-12057: Integrate Community PR (#138)

client/connector/HarnessConnector.cs, ff-netF48-server-sdk.csproj
Currently the SDK will log a generic HTTP error string if the config host name does not exist:
`An error occurred while sending the request.`
Update the SDK to catch `HttpRequestException` and log more details to make it easier to diagnose DNS issues.
`[13:43:23 ERR] HttpRequestException: nodename nor servname provided, or not known (i_dot_not_exist:443) StatusCode=null HttpRequestError=NameResolutionError`
=> feat: [FFM-12553]: Improve logging of DNS errors
