client/Evaluator.cs
This PR contains a fix ported from the Java Server SDK.
=> FFM-1448 - Fix ported.

client/api/CfClient.cs, client/api/Event.cs, client/api/InnerClient.cs, client/api/Message.cs, client/api/SSEListener.cs, client/connector/Connector.cs
PR between integration branch and interface_refactor. The goal of creating multiple pull requests is to have a better overview of changes. The intermittent state of the integration branch will not be fully functional. 
**PR #1:** 
CfClient interface changed. Introducing methods to subscribe for notifications, update message or provide external Connector functionality.
CfClient behaves as proxy class to InternalClient class 
Upcoming pull requests
PR #2: 
Refactoring InnerClient into separate modules responsible for pulling, sse, evaluation.
Implementation and integration of Harness Connector 
PR #3:
Unit testing
=> Update CFClient interface to reflect changes in Java server side SDK

client/api/Evaluator.cs, tests/ff-server-sdk-test/EvaluatorTest.cs, tests/ff-server-sdk-test/TestModel.cs
- Unit tests are not executed one by one and reported as a list of passed tests.
- Merged change from Java regarding segment includes verification.
=> Update unit tests to execute one by one. Fix execution of segments includes.

client/api/CfClient.cs, client/api/InnerClient.cs, tests/ff-server-sdk-example/Program.cs
Updating interface for backward compatibility.
- Initialize method is now asynchronous
- After creating CfClient user should call new function WaitAndInitialize to start authentication and optionally wait for initialization completion.
=> Interface update

Properties/AssemblyInfo.cs, README.md, ff-netF48-server-sdk.csproj
- Readme file updated to include recent changes.
- Nuget specification updated, to upload first use VS to increase NuGet version number and generate ff-netF48-server-sdk.1.0.8.nupkg file.
=> Readme update

README.md, docs/further_reading.md, examples/getting_started/.idea/.idea.getting_started.dir/.idea/.gitignore, examples/getting_started/.idea/.idea.getting_started.dir/.idea/encodings.xml, examples/getting_started/.idea/.idea.getting_started.dir/.idea/indexLayout.xml, examples/getting_started/.idea/.idea.getting_started.dir/.idea/vcs.xml, examples/getting_started/Program.cs, examples/getting_started/getting_started.csproj
- This adds a Getting Started example that is inlien with other SDKS
- Updated the README and moved extra information into 'Further Reading'
- Added 'docker' command that can be used to test the getting started app
=> (maint) Update Docs and Examples

examples/getting_started/getting_started.csproj
Update the dot net sdk example to point to the latest fixed version
=> (FFM-3651) Update dot net sdk to latest in example app

docs/further_reading.md
This specifies the main default configuration that can be controlled with the SDKs
=> [FFM-3359]: Add default configuration for .net

client/api/Config.cs, examples/getting_started/Program.cs, examples/getting_started/getting_started.csproj, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-example/Program.cs, tests/ff-server-sdk-test/ConfigTest.cs, tests/ff-server-sdk-test/EvaluatorTest.cs
Set metric default setting to true.
=> FFM-3520 Fix Metric Event Default Setting

README.md, examples/getting_started/Program.cs
Update the target name, identifier and attribute to match the new default standard for all sdks
=> (FFM-3759) Update target naming

README.md, examples/getting_started/getting_started.csproj, tests/README.md
Removed reference to the Debug folder.
=> FFM-4306 Fix getting_started

client/api/Evaluator.cs, examples/getting_started/getting_started.csproj, ff-netF48-server-sdk.csproj
**What**
Change to in operator logic, so that we check against the array and not first value in the array
[FFM-4358](https://harness.atlassian.net/browse/FFM-4358)
**Why**
We were only checking against the first value in an array, rather than all values
=> FFM-4358 - Change IN operator clause logic

ff-netF48-server-sdk.csproj
Bump csproj version for 1.1.5 release
=> (MAINT) Bump package version

.config/dotnet-tools.json, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
This adds the junit repoter and covert test coverage packages
=> [FFM-5463]: Add Junit support to .net

ff-netF48-server-sdk.csproj
What
Update csproj build files and metadata with latest version numbers
Why
Ensure artifacts are published correctly with right version
Testing
Manual - smoke tested example with some basic flags
=> [FFM-5541] Update build files for 1.1.6 release

ff-netF48-server-sdk.csproj
Remove references to Serilog which is breaking the build
=> FFM-8686 Fix csproj file

client/api/Evaluator.cs
FFM-7871 - Multiple pre-reqs not working correctly
What
Fix loop which doesn't check the result of the prereq check function
Why
The loop should abort immediately when false is returned
Testing
=> FFM-7871 - Multiple pre-reqs not working correctly

ff-netF48-server-sdk.csproj
[FFM-9473] - Update Newtonsoft.Json to version 13.0.3
What
Update Newtonsoft.Json to version 13.0.3
Why
Get the latest security updates
Testing
[FFM-9473]: https://harness.atlassian.net/browse/FFM-9473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FFM-9473] - Update Newtonsoft.Json to version 13.0.3

examples/getting_started/Program.cs, examples/getting_started/getting_started.csproj
What
getting started is trying to pull 1.2.0 which isn't published yet
=> small fix for failing publish task

client/api/PollingProcessor.cs, client/api/Repository.cs, client/connector/EventSource.cs, ff-netF48-server-sdk.csproj, tests/ff-server-sdk-test/EvaluatorTest.cs, tests/ff-server-sdk-test/StorageRepositoryTest.cs, tests/ff-server-sdk-test/api/CfClientTest.cs
**What**
- Improve cache locking and synchronization
- Improve stream error handling
- Increase capacity of dictionary
- Additional cache recovery checks
**Why**
We're getting reports of cache not being setup correctly in the field.
**Testing**
Unit + Manual + Testgrid
=> [FFM-11089] - Cache & exception handling improvements

client/api/Evaluator.cs
**What**
Updates the previous commit to add a check so we don't return true on empty clauses
=> [FFM-11242] - Fix for previous commit

client/connector/HarnessConnector.cs, examples/getting_started/getting_started.csproj, examples/tls-example/tls-example.csproj, ff-netF48-server-sdk.csproj, tests/evaluation-load-test/evaluation-load-test.csproj, tests/ff-server-sdk-test/ff-server-sdk-test.csproj
This PR is to update the project to support .NET 8 and address a version conflict issue in "System.IdentityModel.Tokens.Jwt" in projects using the .NET 8 version of the library. See Issue: #137 for details.
=> Update projects to target .NET 8.0 and upgrade packages
